//
// Copyrigh 2022 Anthony Paul Astolfi
//

var releaseNavPathPattern = /^\/[^\/]*/;

window.addEventListener('load', function() {
    if ($('#releaseNavSelectBox').length !== 0) {
        console.log('already ran releaseNav');
        return;
    }
    var navBarElem = $('.md-header nav');
    var releases = releaseNavOptions;

    var actualRelease = location.pathname.match(releaseNavPathPattern)[0];
    var i = releases.indexOf(actualRelease.substr(1));
    var tmp = releases[i];
    releases[i] = releases[0];
    releases[0] = tmp;

    navBarElem.append(
        '<select id="releaseNavSelectBox" name="releaseNav"' +
        ' onchange="location.pathname = location.pathname.replace(releaseNavPathPattern, this.value);">' +
        jQuery
            .map(
                releases,
                function(ver) {
                    return '<option value="/' + ver + '">' + ver + '</option>'
                })
            .join('') +
        '</select>');
    
    // Fix up the autogenerated links to include the version directory.
    //
    $('a[href^="/_autogen"]').each(function(){
        var url = $(this).attr("href");
        $(this).attr("href", actualRelease + url);
    });
});
